"""add publish time

Revision ID: 106f4e53c438
Revises: 46c42db38eb6
Create Date: 2015-11-25 10:01:11.148875

"""

# revision identifiers, used by Alembic.
revision = '106f4e53c438'
down_revision = '46c42db38eb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('edit_time', sa.DateTime(), nullable=True))
    op.add_column('articles', sa.Column('publish_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_articles_publish_time'), 'articles', ['publish_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_publish_time'), table_name='articles')
    op.drop_column('articles', 'publish_time')
    op.drop_column('articles', 'edit_time')
    ### end Alembic commands ###
