"""mod User_Role_Relation

Revision ID: 167c994c99c7
Revises: 297418e0aa43
Create Date: 2015-11-19 15:52:48.355307

"""

# revision identifiers, used by Alembic.
revision = '167c994c99c7'
down_revision = '297418e0aa43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_role_relation_operate_time'), 'user_role_relation', ['operate_time'], unique=False)
    op.drop_index('operate_id', table_name='user_role_relation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('operate_id', 'user_role_relation', ['operate_id'], unique=True)
    op.drop_index(op.f('ix_user_role_relation_operate_time'), table_name='user_role_relation')
    ### end Alembic commands ###
