"""add role,permission

Revision ID: 1782e1af3cc2
Revises: 41f54a303001
Create Date: 2015-11-16 17:37:49.408278

"""

# revision identifiers, used by Alembic.
revision = '1782e1af3cc2'
down_revision = '41f54a303001'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=60), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rolename')
    )
    op.create_table('user_role_relation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('operate_id', sa.Integer(), nullable=True),
    sa.Column('operate_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('operate_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_relation')
    op.drop_table('roles')
    ### end Alembic commands ###
