"""User add confirmed

Revision ID: 23de64edbef2
Revises: None
Create Date: 2015-11-12 17:11:03.758601

"""

# revision identifiers, used by Alembic.
revision = '23de64edbef2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
