"""add ask_for_lift_ban

Revision ID: 297418e0aa43
Revises: 4f28090745df
Create Date: 2015-11-18 15:43:36.027794

"""

# revision identifiers, used by Alembic.
revision = '297418e0aa43'
down_revision = '4f28090745df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ask_for_lift_ban', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ask_for_lift_ban')
    ### end Alembic commands ###
