"""add article page view

Revision ID: 2a1c4da978f8
Revises: 4058a1c2b44d
Create Date: 2015-11-26 10:34:54.369011

"""

# revision identifiers, used by Alembic.
revision = '2a1c4da978f8'
down_revision = '4058a1c2b44d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('page_view', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'page_view')
    ### end Alembic commands ###
