"""add article

Revision ID: 36c61afe3519
Revises: 519e5b696ae4
Create Date: 2015-11-24 16:50:25.083234

"""

# revision identifiers, used by Alembic.
revision = '36c61afe3519'
down_revision = '519e5b696ae4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.UnicodeText(), nullable=False),
    sa.Column('digest', sa.UnicodeText(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    ### end Alembic commands ###
