"""add Follow

Revision ID: 4058a1c2b44d
Revises: 106f4e53c438
Create Date: 2015-11-25 16:45:58.773600

"""

# revision identifiers, used by Alembic.
revision = '4058a1c2b44d'
down_revision = '106f4e53c438'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_relation',
    sa.Column('star_id', sa.Integer(), nullable=False),
    sa.Column('fans_id', sa.Integer(), nullable=False),
    sa.Column('timesamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fans_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['star_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('star_id', 'fans_id')
    )
    op.create_index(op.f('ix_follow_relation_timesamp'), 'follow_relation', ['timesamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_relation_timesamp'), table_name='follow_relation')
    op.drop_table('follow_relation')
    ### end Alembic commands ###
