"""add login time

Revision ID: 41f54a303001
Revises: 23de64edbef2
Create Date: 2015-11-14 10:56:34.386250

"""

# revision identifiers, used by Alembic.
revision = '41f54a303001'
down_revision = '23de64edbef2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('register_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_time')
    op.drop_column('users', 'last_login_time')
    ### end Alembic commands ###
