"""add user banned

Revision ID: 4f28090745df
Revises: 1782e1af3cc2
Create Date: 2015-11-18 09:59:26.930530

"""

# revision identifiers, used by Alembic.
revision = '4f28090745df'
down_revision = '1782e1af3cc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    ### end Alembic commands ###
