"""xxx

Revision ID: 519e5b696ae4
Revises: 628fb686363
Create Date: 2015-11-21 23:38:06.202680

"""

# revision identifiers, used by Alembic.
revision = '519e5b696ae4'
down_revision = '628fb686363'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    ### end Alembic commands ###
