"""mod comment

Revision ID: 7930460082c
Revises: 14f8ed238643
Create Date: 2015-11-26 16:12:37.795711

"""

# revision identifiers, used by Alembic.
revision = '7930460082c'
down_revision = '14f8ed238643'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    ### end Alembic commands ###
